# Generated by Django 5.0.4 on 2024-05-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prodapp',
        ),
        migrations.RemoveField(
            model_name='products',
            name='selling_price',
        ),
    ]
