# Generated by Django 5.0.4 on 2024-05-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='description',
            new_name='testimony',
        ),
    ]
